# Generated by Django 4.2.4 on 2023-08-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_colors_person_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colors'),
        ),
    ]
